#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(${READLINK_BIN} -f $(dirname ${0})/..)"
  docker run -v ${SOURCE_PATH}:/data fsfe/reuse:latest lint
else
  cd $SOURCE_PATH
  reuse lint
fi