#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -ex

binary=docforge-linux-amd64
if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
  binary=docforge-darwin-amd64
else
  READLINK_BIN="readlink"
fi

if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(${READLINK_BIN} -f "$(dirname "${0}")/..")"
fi

if [[ -z "${BINARY}" ]]; then
  BINARY="${SOURCE_PATH}/bin"
else
  BINARY="${BINARY}/bin"
fi

if [[ ! -d "${BINARY}/rel" ]]; then
  echo "${BINARY}/rel does not exist. Forgot to build the binaries before running this?"
  exit 1
fi

"$BINARY/rel/${binary}" gen-cmd-docs -d "$SOURCE_PATH/docs/cmd-ref"
