#!/usr/bin/env bash

# SPDX-FileCopyrightText: Contributors to the Gardener project
#
# SPDX-License-Identifier: Apache-2.0

getGitHubToken() {
  # Check if gardener-ci is available (in local setup)
  command -v gardener-ci >/dev/null && gardenci="true" || gardenci=""
  if [[ $gardenci == "true" ]]; then
    # Get a (round-robin) random technical GitHub user credentials
    technicalUser=$(gardener-ci config model_element --cfg-type github --cfg-name "${1}" --key credentials | sed -e "s/^GithubCredentials //" -e "s/'/\"/g")
    if [[ -n "${technicalUser}" ]]; then
      # get auth token and strip lead/trail quotes
      authToken="$(jq -r '.authToken' <<< "$technicalUser")"
      echo "${authToken}"
    fi
  fi
}

if [ -z "${GITHUB_TOKEN:-}" ]; then
  TOKEN=$(getGitHubToken github_com)
else
  TOKEN=${GITHUB_TOKEN}
fi
test "$TOKEN" #fail fast
echo Token accepted

docforge_repo_path="$(readlink -f "$(dirname "${0}")/..")"

GITHUB_OAUTH_TOKEN=$TOKEN "${docforge_repo_path}/test/e2e/diff.sh"
