#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

getGitHubToken() {
  # Check if gardener-ci is available (in local setup)
  command -v gardener-ci >/dev/null && gardenci="true" || gardenci=""
  if [[ $gardenci == "true" ]]; then
    # Get a (round-robin) random technical GitHub user credentials
    technicalUser=$(gardener-ci config model_element --cfg-type github --cfg-name "${1}" --key credentials | sed -e "s/^GithubCredentials //" -e "s/'/\"/g")
    if [[ -n "${technicalUser}" ]]; then
      # get auth token and strip lead/trail quotes
      authToken="$(jq -r '.authToken' <<< "$technicalUser")"
      echo "${authToken}"
    fi
  fi
}

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

docforge_repo_path="$(${READLINK_BIN} -f "$(dirname "${0}")/..")"
website_generator_path="${docforge_repo_path}/../website-generator"
content=${website_generator_path}/hugo/content
PR_content=${website_generator_path}/hugo/branchContent
docforge_bin="${docforge_repo_path}/bin/docforge"

echo Docforge repo: "$docforge_repo_path"

if [[ ! -d "$website_generator_path" ]]; then
  git clone https://github.com/gardener/website-generator.git "$website_generator_path"
fi

echo "Clean old build if done"
rm -rf "$content"
rm -rf "$PR_content"

TOKEN=${GITHUB_OAUTH_TOKEN:-$(getGitHubToken github_com)}
test "$TOKEN" #fail fast
echo Token accepted
export GITHUB_OAUTH_TOKEN=$TOKEN

buildWebsite() {
  LOCAL_BUILD=1 "${docforge_repo_path}/.ci/build" >/dev/null 2>&1
  mv "$docforge_bin" /usr/local/bin/docforge
  SKIP_VALIDATION=true "${website_generator_path}/.ci/build"
}

echo "Building current docforge"
buildWebsite
mv "$content" "$PR_content"

echo "Building master docforge"
pushd "$docforge_repo_path"
git status
git diff
git checkout master
popd
buildWebsite

echo "-------------------------------"
echo "Diff results"
rm -rf "${content}/__resources" 
rm -rf "${PR_content}/__resources" 
diff -r "$content" "$PR_content"
