#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# For the integration-test step the following environment variables are used:
# GIT_OAUTH_TOKEN - used for fetch the content from Github
# INT_TEST_MANIFEST_ORG - used to replace the manifest org to this one. If does not exist, the script will try to get the org from .ci/userlogin
# INT_TEST_MANIFEST_VERSION - used to replace the manifest version to this one. If does not exist, the script will try to get the version from .ci/branch

getGitHubToken() {
  # Check if gardener-ci is available (in local setup)
  command -v gardener-ci >/dev/null && gardenci="true" || gardenci=""
  if [[ $gardenci == "true" ]]; then
    # Get a (round-robin) random technical GitHub user credentials
    technicalUser=$(gardener-ci config model_element --cfg-type github --cfg-name "${1}" --key credentials | sed -e "s/^GithubCredentials //" -e "s/'/\"/g")
    if [[ -n "${technicalUser}" ]]; then
      # get auth token and strip lead/trail quotes
      authToken="$(jq -r '.authToken' <<< "$technicalUser")"
      # get username and strip lead/trail quotes
      username="$(jq -r '.username' <<< "$technicalUser")"
      echo "${username}:${authToken}"
    fi
  fi
}

removeUntestedKeysFromMetadata() {
    metadataFiles="$(find "${1}" -type f)"
    for file in ${metadataFiles}; do 
      content=$(jq 'del(.. | .shaalias?, .weburl?, .path?, .lastmod?, .publishdate?)' "${file}")
      echo "$content" > "${file}"
    done
}

removeHashFromImageName() {
  image="${2}"
  imageName="${image%.*}"
  imageExt="${image##*.}"
  find "${1}" -type f -print0 | xargs -0 sed -i "s/${imageName}_.*${imageExt}/${imageName}\.${imageExt}/g"
  find "${1}" -type f -name "*${imageName}_*.${imageExt}" -execdir mv {} "./${imageName}.${imageExt}" \;
}

diffDirs() {
  if [[ $(uname) == 'Darwin' ]] || [[ $(uname) == *"Linux"* ]]; then
    output="$(diff -r "${1}" "${2}")"
  else
    output="$(fc "${1}" "${2}")"
  fi

  if [[ -n "${output}" ]]; then
    echo "${output}"
    exit 1
  else
    echo "  Passed"
  fi
}

testGeneratedTrees() {
  echo "Testing generated tree" >&2
  diffDirs "${1}" "${2}"

  echo "Testing generated metadata" >&2
  echo "Removing contributors file" >&2
  if [[ -f "${3}/contributors.json" ]]; then
    rm "${3}/contributors.json"
  fi
  if [[ -f "${4}/contributors.json" ]]; then
    rm "${4}/contributors.json"
  fi
  diffDirs "${3}" "${4}"
}

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

docforge_repo_path="$(${READLINK_BIN} -f "$(dirname "${0}")/..")"
int_test_dir="${docforge_repo_path}/integration-test"
int_test_expected_tree_dir="${int_test_dir}/expected-tree"
int_test_expected_metadata_dir="${int_test_dir}/expected-metadata"
int_test_output_tree_dir="${int_test_dir}/generated-tree"
int_test_output_metadata_dir="${int_test_dir}/generated-metadata"
int_test_manifest="${int_test_dir}/manifest.yaml"

rm -rf "${int_test_output_tree_dir}"
rm -rf "${int_test_output_metadata_dir}"

# build docforge
echo "Building docforge"
LOCAL_BUILD=1 "${docforge_repo_path}/.ci/build" >/dev/null 2>&1
docforge_bin="${docforge_repo_path}/bin/docforge"

echo "Docforge version: $(${docforge_bin} version)"

org=""
mainBranch=""

if [[ -n "${INT_TEST_MANIFEST_ORG}" ]] && [[ -n "${INT_TEST_MANIFEST_VERSION}" ]]; then
  echo "Retrieving org and mainBranch from env vars"
  org=${INT_TEST_MANIFEST_ORG}
  mainBranch=${INT_TEST_MANIFEST_VERSION}
elif [[ -f "${docforge_repo_path}/.git/userlogin" ]] && [[ -f "${docforge_repo_path}/.git/branch" ]]; then
  echo "Retrieving org and mainBranch from ${docforge_repo_path}/.git"
  org=$(cat "${docforge_repo_path}/.git/userlogin")
  mainBranch=$(cat "${docforge_repo_path}/.git/branch")
else
  echo "Using default org and mainBranch"
  org="gardener"
  mainBranch="master"
fi

echo "Manifest org: ${org}"
echo "Manifest mainBranch: ${mainBranch}"

if [[ -z "${org}" ]] || [[ -z "${mainBranch}" ]]; then
  exit 1
fi

GIT_OAUTH_TOKEN=${GIT_OAUTH_TOKEN:-$(getGitHubToken github_com)}
test "$GIT_OAUTH_TOKEN" #fail fast

# Run docforge command with Git handler
echo "Run ${docforge_bin}"
${docforge_bin} -f "${int_test_manifest}" -d "${int_test_output_tree_dir}" --hugo --github-oauth-token "${GIT_OAUTH_TOKEN}" --github-info-destination ../generated-metadata --variables "org=${org},version=${mainBranch}"

#Remove untested metadata keys
removeUntestedKeysFromMetadata "${int_test_expected_metadata_dir}"
removeUntestedKeysFromMetadata "${int_test_output_metadata_dir}"
removeHashFromImageName "${int_test_expected_tree_dir}" "gardener-docforge-logo.png"
removeHashFromImageName "${int_test_output_tree_dir}" "gardener-docforge-logo.png"

echo "Testing Git Handler"
testGeneratedTrees "${int_test_expected_tree_dir}" "${int_test_output_tree_dir}" "${int_test_expected_metadata_dir}" "${int_test_output_metadata_dir}"
