#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# For the test step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

if [[ $(uname) == 'Darwin' ]]; then
  READLINK_BIN="greadlink"
else
  READLINK_BIN="readlink"
fi

if [[ -z "${SOURCE_PATH}" ]]; then
  SOURCE_PATH="$(${READLINK_BIN} -f "$(dirname "${0}")/..")"
  export SOURCE_PATH
else
  SOURCE_PATH="$(${READLINK_BIN} -f "${SOURCE_PATH}")"
  export SOURCE_PATH
fi

cd "${SOURCE_PATH}"

# Get the Ginkgo (test framework) binary to be able to execute the tests.
go install github.com/onsi/ginkgo/ginkgo@latest

executable=${GOPATH}/bin/ginkgo
if [ -z ${GOPATH+x} ]; then
  echo "GOPATH not set. Trying with HOME/go/bin"
  if [ -f "${HOME}/go/bin/ginkgo" ]; then
    executable="${HOME}/go/bin/ginkgo"
  else
    echo "HOME/go/bin/ginkgo not found. Set GOPATH"
    Exit 1
  fi
fi

###############################################################################

COVER_FLAG=""
if [[ -n "$COVERAGE" ]]; then
  COVER_FLAG="-cover"
fi

$executable ${COVER_FLAG} -r cmd pkg

echo "Done"