#!/bin/bash -eu

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

VERSION="${1:-$($(dirname $0)/get-next-version)}"
COMMIT="${2:-true}"

echo "Bumping version to $VERSION"
echo $VERSION > $(dirname $0)/../VERSION

# commit
if [[ $COMMIT == true ]]; then
  git status
  read -p "Continue (y/n)? " response
  if [[ "$response" =~ ^(yes|y) ]]; then
    git add .
    git commit -m "Bump version to $VERSION"
  fi
  git status
fi
