#!/bin/bash -e

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

function increment() {
  echo $(awk "BEGIN {print $1+1; exit}")
}

TYPE="${1:-default}"

CURRENT_VERSION="$(cat $(dirname $0)/../VERSION)"
MAJOR="$(echo $CURRENT_VERSION | sed -E 's/^v([0-9]*).*$/\1/')"
MINOR="$(echo $CURRENT_VERSION | sed -E 's/^.*\.([0-9]*)\..*$/\1/')"
PATCH="$(echo $CURRENT_VERSION | sed -E 's/^.*\.([0-9]*)$/\1/')"

if [[ $TYPE == "hotfix" || "$(git rev-parse --abbrev-ref HEAD)" == *release* ]]; then
  echo v$MAJOR.$MINOR.$(increment $PATCH)
else
  PATCH=0
  echo v$MAJOR.$(increment $MINOR).$PATCH
fi

